import React from 'react';
import { GeneratedReport } from '../types';
import { ExportControls } from './ExportControls';
import { useExecutiveIntelligence } from '../hooks/useExecutiveIntelligence';

interface ReportHistoryPanelProps {
  reports: GeneratedReport[];
}

export const ReportHistoryPanel: React.FC<ReportHistoryPanelProps> = ({ reports }) => {
  const { updateReportExportStatus } = useExecutiveIntelligence();

  if (reports.length === 0) {
    return (
      <div className="bg-slate-800/50 rounded-xl border border-slate-700/50 p-8 text-center text-slate-500">
        No reports have been generated yet.
      </div>
    );
  }

  return (
    <div className="bg-slate-800/50 rounded-xl border border-slate-700/50 overflow-hidden flex flex-col h-full">
      <div className="p-4 border-b border-slate-700/50 bg-slate-800/80">
        <h3 className="font-semibold text-slate-200">Report History</h3>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left text-sm text-slate-400">
          <thead className="text-xs uppercase bg-slate-900/50 text-slate-500 border-b border-slate-700/50">
            <tr>
              <th className="px-4 py-3">Report Type</th>
              <th className="px-4 py-3">Generated Time</th>
              <th className="px-4 py-3">Generated By</th>
              <th className="px-4 py-3">Size</th>
              <th className="px-4 py-3">Status</th>
              <th className="px-4 py-3 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-700/50">
            {reports.map((report) => (
              <tr key={report.id} className="hover:bg-slate-800/50 transition-colors">
                <td className="px-4 py-3 font-medium text-slate-200">{report.type}</td>
                <td className="px-4 py-3">{new Date(report.generatedTime).toLocaleString()}</td>
                <td className="px-4 py-3">{report.generatedBy}</td>
                <td className="px-4 py-3">{report.reportSizeKb.toFixed(1)} KB</td>
                <td className="px-4 py-3">
                  <span
                    className={`px-2 py-1 rounded-full text-[10px] uppercase font-bold ${
                      report.exportStatus === 'Exported'
                        ? 'bg-green-500/20 text-green-400'
                        : report.exportStatus === 'Pending'
                          ? 'bg-amber-500/20 text-amber-400'
                          : 'bg-slate-700 text-slate-300'
                    }`}
                  >
                    {report.exportStatus}
                  </span>
                </td>
                <td className="px-4 py-3 flex justify-end">
                  <ExportControls
                    report={report}
                    onExportComplete={(id) => updateReportExportStatus(id, 'Exported')}
                  />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};
